# Generated by Django 5.2 on 2025-05-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(
                ('user', models.F('author')), _negated=True), name='prevent_self_subscription'),
        ),
    ]
