# Generated by Django 5.2 on 2025-05-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription_prevent_self_subscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='prevent_self_subscription',
        ),
    ]
